In [103]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [104]:
from sklearn.datasets import load_iris

In [105]:
from sklearn.model_selection import train_test_split

In [106]:
x, y = load_iris(return_X_y = True)

In [107]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [108]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 42)

In [109]:
print(np.unique(x_train[:3]))

[1.  1.5 1.8 2.4 2.8 3.1 3.7 5.1 5.5 6.3 6.4]


In [110]:
from sklearn.naive_bayes import GaussianNB

In [111]:
gnb = GaussianNB()

In [112]:
gnb.fit(x_train, y_train)

GaussianNB()

In [113]:
y_pred = gnb.predict(x_test)

In [114]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [115]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 12  0]
 [ 0  1 13]]
0.9777777777777777
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      1.00      0.96        12
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.97      0.98      0.97        45
weighted avg       0.98      0.98      0.98        45



In [116]:
# Using Nb in tips dataset

In [183]:
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [186]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [187]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [188]:
 y =df['time']

In [189]:
y

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...  
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [190]:
x = df

In [191]:
x.drop("time", axis=1, inplace = True)

In [192]:
from sklearn.model_selection import train_test_split

In [193]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=42)

In [194]:
x_train

total_bill   tip     sex smoker  day  size
234       15.53  3.00    Male    Yes  Sat     2
227       20.45  3.00    Male     No  Sat     4
180       34.65  3.68    Male    Yes  Sun     4
5         25.29  4.71    Male     No  Sun     4
56        38.01  3.00    Male    Yes  Sat     4
..          ...   ...     ...    ...  ...   ...
106       20.49  4.06    Male    Yes  Sat     2
14        14.83  3.02  Female     No  Sun     2
92         5.75  1.00  Female    Yes  Fri     2
179       34.63  3.55    Male    Yes  Sun     2
102       44.30  2.50  Female    Yes  Sat     3

[170 rows x 6 columns]

In [195]:
from sklearn.preprocessing import LabelEncoder

In [196]:
le = LabelEncoder()

In [199]:
for col in ['sex', 'smoker', 'day']:
    x_train[col] = le.fit_transform(x_train[col])

In [200]:
for col in ['sex', 'smoker', 'day']:
    x_test[col] = le.fit_transform(x_test[col])

In [201]:
y_train = le.fit_transform(y_train)

In [202]:
y_test = le.fit_transform(y_test)

In [203]:
y_train

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [204]:
x_test

total_bill   tip  sex  smoker  day  size
24        19.82  3.18    1       0    1     2
6          8.77  2.00    1       0    2     2
153       24.55  2.00    1       0    2     4
211       25.89  5.16    1       1    1     4
198       13.00  2.00    0       1    3     2
..          ...   ...  ...     ...  ...   ...
165       24.52  3.48    1       0    2     3
154       19.77  2.00    1       0    2     4
216       28.15  3.00    1       1    1     5
79        17.29  2.71    1       0    3     2
29        19.65  3.00    0       0    1     2

[74 rows x 6 columns]

In [205]:
from sklearn.naive_bayes import GaussianNB

In [206]:
gnb = GaussianNB()

In [207]:
gnb.fit(x_train, y_train)

GaussianNB()

In [208]:
y_pred = gnb.predict(x_test)

In [209]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [210]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[53  3]
 [ 2 16]]
0.9324324324324325
              precision    recall  f1-score   support

           0       0.96      0.95      0.95        56
           1       0.84      0.89      0.86        18

    accuracy                           0.93        74
   macro avg       0.90      0.92      0.91        74
weighted avg       0.93      0.93      0.93        74



Solving TIPS using One Hot Encoding

In [141]:
df = sns.load_dataset("tips")

In [142]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [172]:
x = df.drop(columns = "time")
y = df['time']

In [173]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB

In [176]:
cat_cols = ['day', 'sex', 'smoker']
preprocessor = ColumnTransformer(transformers = [('cat', OneHotEncoder(drop="first"), cat_cols)], remainder = "passthrough")

In [177]:
model = Pipeline(steps = [("pre", preprocessor), ("nb", GaussianNB())])

In [178]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=42)

In [179]:
model.fit(x_train, y_train)

Pipeline(steps=[('pre',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('cat',
                                                  OneHotEncoder(drop='first'),
                                                  ['day', 'sex', 'smoker'])])),
                ('nb', GaussianNB())])

In [180]:
y_pred = model.predict(x_test)

In [181]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[52  0]
 [ 3 19]]
0.9594594594594594
              precision    recall  f1-score   support

      Dinner       0.95      1.00      0.97        52
       Lunch       1.00      0.86      0.93        22

    accuracy                           0.96        74
   macro avg       0.97      0.93      0.95        74
weighted avg       0.96      0.96      0.96        74



In [211]:
# Solving BernaulliNB

In [212]:
from sklearn.naive_bayes import BernoulliNB

In [213]:
data = {
    "has_free": [1, 0, 1, 0, 1],
    "has_win": [1, 0, 1, 0, 0],
    "has_offer": [1, 0, 0, 0, 1],
    "is_spam": [1, 0, 1, 0, 1]
}
df = pd.DataFrame(data)

In [215]:
x = df.drop("is_spam", axis=1)
y = df["is_spam"]

In [216]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state=42)

In [218]:
model = BernoulliNB()
model.fit(x_train, y_train)

BernoulliNB()

In [219]:
y_pred = model.predict(x_test)

In [220]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[1 0]
 [0 1]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



In [221]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 🧪 Tough synthetic dataset
data = {
    "young":                 [1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0],
    "has_job":              [0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1],
    "student":              [1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0],
    "credit_rating_good":   [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1],
    "uses_social_media_daily": [1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0],
    "buys_insurance":       [0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1]
}

df = pd.DataFrame(data)

# 🧠 Features and target
X = df.drop("buys_insurance", axis=1)
y = df["buys_insurance"]

# 🔀 Split into training/testing
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.3)

# 🏹 Bernoulli Naive Bayes
model = BernoulliNB()
model.fit(X_train, y_train)

# 📊 Prediction
y_pred = model.predict(X_test)

# 📈 Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


Accuracy: 1.0

Confusion Matrix:
 [[4 0]
 [0 1]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         1

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5

